### ISSUE TITLE
Changes in Paperless 1.10

### ISSUE THREAD

**Issue by ignis-draco** [paperless-ngx/ansible#13]
As of 1.10, the systemd scripts have changed.

**Comment by stevenengland** [comment]
... and at least one implication of this is that version > 1.10 cannot be deployed with this role. For example the scheduler service will fail with
`Unknown command: 'qcluster'`
because it uses the old service unit file...

**Comment by ignis-draco** [comment]
Unfortunately, I have no idea where in the ansible scripts I need to make the changes. 

The following scripts must be copied under /etc/systemd/system: 
paperless-consumer.service
paperless-scheduler.service
paperless-task-queue.service
paperless-webserver.service

The start field in the paperless-scheduler.service file must be changed to  
ExecStart = /opt/paperless-ngx/.venv/bin/celery --app paperless beat --loglevel INFO

**Comment by muued** [comment]
see #12

**Comment by stevenengland** [comment]
Hi everybody, from my point of view this issue is now solved via #27 -> Feel free to reopen the issue if there is something I forgot
