### ISSUE TITLE
tika service seems to be unreachable

### ISSUE THREAD

**Issue by fbim-genosr** [paperless-ngx/ansible#130]
Hey everybody,

though, Tika is enabled via 

`paperless_ngx_conf_tika_enabled: true`

the service seems to be unreachable on the host, the ansible playbook is running on.

`Error occurred while consuming document some-email.eml: Could not parse content with tika server at http://localhost:9998: [Errno 111] Connection refused`

How can I check if Tika is running?

**Comment by stevenengland** [comment]
Hi @fbim-genosr ,

thank you for reporting. Right now this role does not handle the installation of Tika because it is not a core component of paperless ngx.
