### ISSUE TITLE
Use rebuilt ansible role to follow conventions & enable easier maintenance.

### ISSUE THREAD

**Issue by r-pufky** [paperless-ngx/ansible#3]
Hello Folks,

I was going to submit this to the original paperless-ng repo, but it seems like that has had no action from the original author for quite some time. I've re-written the entire ansible role to conform to latest ansible specs, and have cleaned up a lot of the original work. This is currently published on ansible-galaxy for paperless-ng, but would like to include in NGX, as I am planning on moving to NGX when it gets a bit more stable.

The ansible playbook is here: https://github.com/r-pufky/ansible_paperlessng

Any new work added in this repo would need to be evaluated and added for import if missing.

**Comment by shamoon** [comment]
Thanks for your interest. I’m not sure if there are others here capable of maintaining ansible-related stuff which is why it was moved to this repo

**Comment by r-pufky** [comment]
No worries. I'll play around with NGX and update my role accordingly, then shoot in a pull request to see how it looks -- shouldn't be too hard, just need some free time.

**Comment by qcasey** [comment]
Hello @r-pufky, we've pulled together a few sources and merged a working ansible install to `main`. If you would still like to test and/or contribute we would appreciate your input.
