### ISSUE TITLE
TASK Compare versions of installed ansible and required ansible does not recognize ansible-core package

### ISSUE THREAD

**Issue by Tronde** [paperless-ngx/ansible#51]
Hi,  
I was trying to use Fedora 37 with `ansible-core` package installed as Ansible controller to run this role to install paperless-ngx to a Debian node. The playbook failed at the task mentioned in the title of this issue.

## What Ansible version do you use?

~~~
$ ansible-playbook --version
ansible-playbook [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tronde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/tronde/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
~~~

## What does the playbook looks like?

~~~
$ cat setup_paperless_ngx.yml 
---
- hosts: paperless-t1
  debugger: on_failed
  vars_files:
    - files/my.vars
  tasks:
    - name: Include role ansible-role-paperless-ngx
      include_role:
        name: ansible-role-paperless-ngx
~~~

## Information from debugger

~~~
TASK [ansible-role-paperless-ngx : Compare versions of installed ansible and required ansible] ***
fatal: [paperless-t1]: FAILED! => {"msg": "The conditional check '_ansible_installed_version.stdout is version_compare(ansible_version_minimum, '>=')' failed. The error was: Input version value cannot be empty"}
[paperless-t1] TASK: ansible-role-paperless-ngx : Compare versions of installed ansible and required ansible (debug)> p task.args
{'msg': '"You must update Ansible to at least 4.0.0 to use this role."\n',
 'that': '_ansible_installed_version.stdout is '
         "version_compare(ansible_version_minimum, '>=')"}
[paperless-t1] TASK: ansible-role-paperless-ngx : Compare versions of installed ansible and required ansible (debug)> p task_vars['ansible_version_minimum']
'4.0.0'
[paperless-t1] TASK: ansible-role-paperless-ngx : Compare versions of installed ansible and required ansible (debug)> p task_vars['_ansible_installed_version.stdout']
***KeyError:KeyError('_ansible_installed_version.stdout')
[paperless-t1] TASK: ansible-role-paperless-ngx : Compare versions of installed ansible and required ansible (debug)> p task_vars['_ansible_installed_version']
{'changed': False,
 'cmd': "python3 -m pip show ansible | grep Version | cut -d ' ' -f 2",
 'delta': '0:00:00.540653',
 'end': '2023-03-27 21:52:17.238333',
 'failed': False,
 'msg': '',
 'rc': 0,
 'start': '2023-03-27 21:52:16.697680',
 'stderr': 'WARNING: Package(s) not found: ansible',
 'stderr_lines': ['WARNING: Package(s) not found: ansible'],
 'stdout': '',
 'stdout_lines': []}
[paperless-t1] TASK: ansible-role-paperless-ngx : Compare versions of installed ansible and required ansible (debug)>
~~~

Since I have installed `ansible-core` from the RPM repository of my distribution and not via `pip` the version check failed and cannot succeed.

I'm not sure whether this is a Bug or a missing Feature. As the ansible community package depends on the ansible-core package [0] and Ansible 7.x is based on ansible-core 2.14 [1] my installation should meet the requirements.

I appreciate if you take the time to look into it. Do you think you can change the role, so it will work with ansible-core?

Best regards,  
Tronde

[0] [Releases and maintenance](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#)
[1] [Ansible community changelogs](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#id14)

**Comment by Tronde** [comment]
To check the version of the installed and used Ansible you could simply run the command `ansible --version` and parse it's output. This should work regardless whether Ansible was installed from distribution repos or pip.

For Debian 11 with ansible community release installed that gives you:

~~~
$ ansible --version
ansible 2.10.8
[…]
~~~

For Fedora 37 with ansible-core package installed that gives you:

~~~
$ ansible --version
ansible [core 2.14.3]
[…]
~~~

Or maybe the `debug` module could be used to get `ansible_version` to check against.

### Example Playbook

~~~
---
- hosts: localhost
  tasks:
    - name: Debug
      debug:
        msg: "{{ ansible_version }}"
~~~

Output:

~~~
TASK [Debug] *******************************************************************************************
ok: [localhost] => {
    "msg": {
        "full": "2.14.3",
        "major": 2,
        "minor": 14,
        "revision": 3,
        "string": "2.14.3"
    }
}
~~~

What do you think?

**Comment by stevenengland** [comment]
Hi @Tronde ,

thank you for reporting. Indeed I am specifically checking the ansible version because the role uses the community package. Not a lot anymore but a few tasks do. So I think the best way would be an extended check for the ansible package installed (not ansible-core) to meet the complete set of requirements. I will have a look these days.

**Comment by Tronde** [comment]
Am 28. März 2023 22:48:11 MESZ schrieb Steven England ***@***.***>:
>Hi @Tronde ,
>
>thank you for reporting. Indeed I am specifically checking the ansible version because the role uses the community package. Not a lot anymore but a few tasks do. So I think the best way would be an extended check for the ansible package installed (not ansible-core) to meet the complete set of requirements. I will have a look these days.
>

Hi,
Could elaborate which tasks depend on the community package, please? I'm not sure if I got it right. Do they depend on the community package or do they depend on a collection that's shipped included in the community package?

Wouldn't it be possible to list the collection/roles the role depends on? You could mention in the list of requirements which are already included in the ansible community package and which have to be installed in addition to that.

Have a nice day!  
Joerg

**Comment by stevenengland** [comment]
Good point. Sounds reasonable. Sounds like a more precise solution than mine. So I would revert back to check for ansible-core only and list additional dependcies (collections) in the Readme but would not check for their existence? In the Readme: Would it be enough to list them without min. needed version of the collection? Because keeping track of those versions would be tedious...

**Comment by Tronde** [comment]
I'm not sure if you have to check the ansible version at all. IIRC collections are supported beginning with Ansible 2.9. And your role has dependencies to some collection but not to the ansible runtime.

IMHO a list of dependencies in the README.md like the following example should suffice:

- Ansible >= 2.9
- Collection1.name1 >= X.Y
- Collection1.name1 >= Z

The playbook should fail quite early in case of missing collections. But of course you could check if the required collections are there. Vivek Gite wrote a blog on how to do this: [How to check if Ansible collection is installed or not](https://www.cyberciti.biz/faq/see-check-if-ansible-collection-is-installed-not-command/)

Regarding the min. needed version of a collection I would just mention the version you used for testing and assume it would work with newer versions as well (>=). And of course you could ask for help to test with older versions of the collections and adjust the version mentioned in the Readme.md. But in my experience nobody does that because updating to a newer version is the better way in most cases.

**Comment by muued** [comment]
you could add a yaml file listing the required collections (e.g. named requirements.yml, but a file with that name already exists). that would contain:
```
---
roles:
  - name: paperless_ngx.paperless_ngx
collections:
  - name: community.general
  - name: ansible.posix
```
then you could mention that it could be installed using
`ansible-galaxy install -r requirements.yml`
when you don't  specify versions, you need to add `--force` to 'update'

**Comment by stevenengland** [comment]
Okay, I had to do some more considerations but it is now done.

The role now checks that ansible-core is >= a specific version and that the dependent collections are installed. The dependent collections and the ansible version is listed in the readme.

Because of the molecule test pipeline used I had to higher the min. ansible-core version to 2.12 But I think that is okay, because it has a few more advantages. Looking at https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html this role now supports the oldest *maintained* version of ansible-core and the highest supported python version is now 3.10.

**Comment by stevenengland** [comment]
> you could add a yaml file listing the required collections (e.g. named requirements.yml, but a file with that name already exists). that would contain:
> 
> ```
> ---
> roles:
>   - name: paperless_ngx.paperless_ngx
> collections:
>   - name: community.general
>   - name: ansible.posix
> ```
> 
> then you could mention that it could be installed using `ansible-galaxy install -r requirements.yml` when you don't specify versions, you need to add `--force` to 'update'

That sounded very good at first. But then a few aspects came into my mind. 
I think this is only convenient for people that do not gather this role via Ansible Galaxy. If you load the role via Galaxy than you would need to figure out the path where the role was installed to to call the requirements file. No big deal to do so but maybe this will confuse people. Also because there is a parallel dependency management delivered by Galaxy that would be listed in meta/main.yml (but that one can only handle roles, not collections as far as I know). I would also need to maintain a .yml for my CI needs in parallel to the one that can be used by users.

My suggestion: We'll start with a clean Readme section that maybe is already enough for people to get started. If there are any questions in the future about this, we should take another closer look :) 

Agreed?

**Comment by Tronde** [comment]
Hi @stevenengland,  
I confirm that this issue is solved by #53 in [release 1.1.1](https://github.com/paperless-ngx/ansible/releases/tag/1.1.1).

For some background information on role/collection dependencies you could take a look at [#76030](https://github.com/ansible/ansible/issues/76030). Collections have the advantage that you could share roles but modules and plugins, too. For example the Red Hat Private Automation Hub can store collections only but no roles.

Anyway this issue is solved and I close it. Thank you @stevenengland for implementing the change!

**Comment by stevenengland** [comment]
Hi @Tronde , wow, that is a very interesting thread. So it might be desireable to turn standalone roles like this one is into a collection in the future. Good to know.

Until now there are only dependencies on collections that are included in the `ansible` package itself. So anybody who only has `ansible-core` installed on the host machine and wants to use the `ansible-galaxy` command to install roles/collections has to install the `ansible` package and is good to go for this role :)

**Comment by Tronde** [comment]
> Hi @Tronde , wow, that is a very interesting thread. So it might be desireable to turn standalone roles like this one is into a collection in the future. Good to know.

IMHO you are good for now. The additional layer of indirection is not necessary as long as Galaxy supports standalone roles. If you plan to support other hubs like i.e. the Red Hat Private Automation Hub (PAH). you need to wrap it in some collection as PAH only works with collections.

> Until now there are only dependencies on collections that are included in the `ansible` package itself. So anybody who only has `ansible-core` installed on the host machine and wants to use the `ansible-galaxy` command to install roles/collections has to install the `ansible` package and is good to go for this role :)

Or you keep `ansible-core` and just install the collections mentioned in the README.md. That works as well. :-)
