### ISSUE TITLE
Improve documentation on configuring NFS mounts

### ISSUE THREAD

**Issue by SiM22** [paperless-ngx/ansible#6]
Will action if/when my PR is merged. Adding so that I dont forget.

NFS mounting is possible. But there is a lack of documentation. This needs adding

**Comment by stevenengland** [comment]
Hi @SiM22 ,

this role was completely remade in the past month with breaking changes introduced last week. 
For more beackground information have a look at:

* https://github.com/paperless-ngx/ansible/issues/24
* https://github.com/paperless-ngx/ansible/discussions/26
* https://github.com/paperless-ngx/ansible/pull/27

As a result this issue might be obsolete. To have a clean restart in regards of this role I chose to close existing issues that reference this role before #27 . 

**--> Feel free to reopen the issue if there is anything I can do for you.**

Many thanks for your understanding!
